### ISSUE TITLE
The problem for inputfile

### ISSUE THREAD

**Issue by yangziyi1990** [magarveylab/prism-releases#12]
Hi:
    Thank you for your reply. I have received prism.jar file, and can run the prism-releases. However, I ran into another problem. When I input an amino acid sequence, I make an error. So what is the format of the input file for prism-release?

The input file like this:
>NC_003155.5 Streptomyces avermitilis MA-4680 = NBRC 14893, complete sequence
CCCGCGGAGCGGGTACCACATCGCTGCGCGATGTGCAAGCGAACACCCGCGCTGCGCGCGGGTGTTGCGC
TCCCGCTCCGCGGGAGCGCCGGCGGGACGCTGCGCGTCCCGCTCACCTCGGTTGCTGCGCAACCGGGGTG
.......

The problem is this:

Identifying C-11 O-methyltransferase (1) domains...
Identifying C-11 O-methyltransferase (2) domains...
Identifying Amidotransferase domains...
Identifying Phenylalanine ammonia lyase domains...
Identifying Type II polyketide priming acyltransferase domains...
Identifying Ketosynthase III domains...
Analyzing condensation and ketosynthase domains...
2月 08, 2021 3:24:15 下午 ca.mcmaster.magarveylab.wasp.exception.ExceptionHandler throwException
严重: Index 1 out of bounds for length 1
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at ca.mcmaster.magarveylab.prism.blast.BlastSearchReader.read(BlastSearchReader.java:63)
	at ca.mcmaster.magarveylab.prism.blast.BlastpSearch.run(BlastpSearch.java:64)
	at ca.mcmaster.magarveylab.prism.blast.DomainBlastpSearch.run(DomainBlastpSearch.java:53)
	at ca.mcmaster.magarveylab.prism.genome.GenomeSearch.executeBlastpAnalysis(GenomeSearch.java:186)
	at ca.mcmaster.magarveylab.prism.genome.GenomeSearch.run(GenomeSearch.java:80)
	at ca.mcmaster.magarveylab.prism.Prism.analyzeOrfs(Prism.java:159)
	at ca.mcmaster.magarveylab.prism.Prism.run(Prism.java:73)
	at ca.mcmaster.magarveylab.prism.PrismDesktop.main(PrismDesktop.java:98)

EXCEPTION: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1

java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at ca.mcmaster.magarveylab.prism.blast.BlastSearchReader.read(BlastSearchReader.java:63)
	at ca.mcmaster.magarveylab.prism.blast.BlastpSearch.run(BlastpSearch.java:64)
	at ca.mcmaster.magarveylab.prism.blast.DomainBlastpSearch.run(DomainBlastpSearch.java:53)
	at ca.mcmaster.magarveylab.prism.genome.GenomeSearch.executeBlastpAnalysis(GenomeSearch.java:186)
	at ca.mcmaster.magarveylab.prism.genome.GenomeSearch.run(GenomeSearch.java:80)
	at ca.mcmaster.magarveylab.prism.Prism.analyzeOrfs(Prism.java:159)
	at ca.mcmaster.magarveylab.prism.Prism.run(Prism.java:73)
	at ca.mcmaster.magarveylab.prism.PrismDesktop.main(PrismDesktop.java:98)
Analysis complete!
[Prism] Terminated.

Looking forward to your reply!

**Comment by keshavd** [comment]
I don't think there is an issue with your file input format. You can use a properly formatted FASTA with a genomic (nucleotide) sequence. This looks like an error related to your copy of blastp. I would verify that the dependency has been correctly met.

The build of PRISM available here is quite old. If you are using this for academic purposes I highly recommend using the new web client found here: https://prism.adapsyn.com/

**Comment by yangziyi1990** [comment]
Thank you very much! I download the fasta file from the NCBI dataset, and load this file to the prism. Is it because of my blastp version?

**Comment by yangziyi1990** [comment]
Thank you very much! I download the fasta file from the NCBI dataset, and load this file to the prism. Is it because of my blastp version? I use Protein-Protein BLAST 2.11.0+.

**Comment by yangziyi1990** [comment]
Sometimes I use a subset of the FASTA sequence and the program runs fine, but sometimes it with the same error.

**Comment by keshavd** [comment]
Can you send along the fasta file and Ill try to replicate the issue on my end?

**Comment by yangziyi1990** [comment]
OK, the linkage of the fasta file: 
https://www.ncbi.nlm.nih.gov/nuccore/NC_003155.5?report=fasta
Thanks a lot!

**Comment by keshavd** [comment]
This genome file runs fine on my end. I'm using Protein-Protein BLAST 2.2.31+.

**Comment by yangziyi1990** [comment]
Yes, When I use Protein-Protein BLAST 2.4.0+, it works! Thanks you a lot!

But at the end of the program, it has another error. Could it be because I'm using Mac OS?
[DomainsUtil] Found starter KS domain matching TetA_BAE93722_KS1
[DomainsUtil] Found starter KS domain matching TylGI_O33954_KS1
[DomainsUtil] Found starter KS domain matching TetA_BAE93722_KS1
[DomainsUtil] Found starter KS domain matching TetA_BAE93722_KS1
[DomainsUtil] Found starter KS domain matching TylGI_O33954_KS1
[DomainsUtil] Found starter KS domain matching TetA_BAE93722_KS1
[PrismFileWriter] Generated JSON file
Analysis complete!
Writing report for cluster 1 report...
[ClusterReport] Error: no contig graph object
Writing report for cluster 2 report...
[ClusterReport] Error: no contig graph object
Writing report for cluster 3 report...
[ClusterReport] Error: no contig graph object
[DomainsUtil] Found starter KS domain matching TetA_BAE93722_KS1
[DomainsUtil] Found starter KS domain matching TetA_BAE93722_KS1
Writing report for cluster 4 report...
[ClusterReport] Error: no contig graph object
Writing report for cluster 5 report...
[ClusterReport] Error: no contig graph object
Writing report for cluster 6 report...
[ClusterReport] Error: no contig graph object
[SugarReport] Graphing 1 sugar combinations
Writing report for cluster 7 report...
[ClusterReport] Error: no contig graph object
Writing report for cluster 8 report...
[ClusterReport] Error: no contig graph object
Writing report for cluster 9 report...
[ClusterReport] Error: no contig graph object
Writing report for cluster 10 report...
[ClusterReport] Error: no contig graph object
Writing report for cluster 11 report...
[ClusterReport] Error: no contig graph object
Writing report for cluster 12 report...
[ClusterReport] Error: no contig graph object
[DomainsUtil] Found starter KS domain matching TylGI_O33954_KS1
[DomainsUtil] Found starter KS domain matching TylGI_O33954_KS1
Writing report for cluster 13 report...
[ClusterReport] Error: no contig graph object
Writing report for cluster 14 report...
[ClusterReport] Error: no contig graph object
[DomainsUtil] Found starter KS domain matching TetA_BAE93722_KS1
[DomainsUtil] Found starter KS domain matching TetA_BAE93722_KS1
Writing report for cluster 15 report...
[ClusterReport] Error: no contig graph object
Writing report for cluster 16 report...
[ClusterReport] Error: no contig graph object
Writing report for cluster 17 report...
[ClusterReport] Error: no contig graph object
Writing report for cluster 18 report...
[ClusterReport] Error: no contig graph object
Writing report for cluster 19 report...
[ClusterReport] Error: no contig graph object
Writing report for cluster 20 report...
[ClusterReport] Error: no contig graph object
[SugarReport] Graphing 3 sugar combinations
Writing report for cluster 21 report...
[ClusterReport] Error: no contig graph object
[SugarReport] Graphing 3 sugar combinations
Writing report for cluster 22 report...
[ClusterReport] Error: no contig graph object
