### ISSUE TITLE
Run error

### ISSUE THREAD

**Issue by APengs494** [magarveylab/prism-releases#13]
Hi:
 I have downloaded prism.jar file in my centos. 
When I input an amino acid sequence, I make an error.
java -jar prism.jar -a -p -f HGUT-02250.fna -tt -sug -res -rib -w 10000 -o ./

Error: couldn't locate script blastp.sh at filepath /mnt/data1/bgc_qhp/PRISM4_tool_bgc/blast/blastp.sh
ca.mcmaster.magarveylab.prism.util.exception.DependencyException: Error: couldn't locate script blastp.sh at filepath /mnt/data1/bgc_qhp/PRISM4_tool_bgc/blast/blastp.sh
	at ca.mcmaster.magarveylab.prism.PrismDependencyCheck.checkScriptFile(PrismDependencyCheck.java:168)
	at ca.mcmaster.magarveylab.prism.PrismDependencyCheck.checkScripts(PrismDependencyCheck.java:130)
	at ca.mcmaster.magarveylab.prism.PrismDependencyCheck.run(PrismDependencyCheck.java:56)
	at ca.mcmaster.magarveylab.prism.Prism.checkDependencies(Prism.java:119)
	at ca.mcmaster.magarveylab.prism.Prism.run(Prism.java:71)
	at ca.mcmaster.magarveylab.prism.PrismDesktop.main(PrismDesktop.java:98)

EXCEPTION: ca.mcmaster.magarveylab.prism.util.exception.DependencyException: Error: couldn't locate script blastp.sh at filepath /mnt/data1/bgc_qhp/PRISM4_tool_bgc/blast/blastp.sh

ca.mcmaster.magarveylab.prism.util.exception.DependencyException: Error: couldn't locate script blastp.sh at filepath /mnt/data1/QinHaiPeng/bgc_qhp/PRISM4_tool_bgc/WebContentDirectory/blast/blastp.sh
	at ca.mcmaster.magarveylab.prism.PrismDependencyCheck.checkScriptFile(PrismDependencyCheck.java:168)
	at ca.mcmaster.magarveylab.prism.PrismDependencyCheck.checkScripts(PrismDependencyCheck.java:130)
	at ca.mcmaster.magarveylab.prism.PrismDependencyCheck.run(PrismDependencyCheck.java:56)
	at ca.mcmaster.magarveylab.prism.Prism.checkDependencies(Prism.java:119)
	at ca.mcmaster.magarveylab.prism.Prism.run(Prism.java:71)
	at ca.mcmaster.magarveylab.prism.PrismDesktop.main(PrismDesktop.java:98)
Analysis complete!
[Prism] Terminated.

Besides downloading prism.jar, do I need to install BLAST?
or
How to install with source code (gz.tar file)

**Comment by nishanthmerwin** [comment]
Yes, BLAST is a required installation. See the README for all required dependencies:


> Core dependencies include HMMER (3.1) and BLAST (2.2.25+). Optional but highly recommended dependencies include BioPerl (1.006924) for GenBank file input, Prodigal (2.6.3) for prokaryotic open reading frame prediction, and FIMO (for ribosomally produced and post-translationally modified peptide precursor cleavage).
