### ISSUE TITLE
muscle_check.sh no such file or directory

### ISSUE THREAD

**Issue by zorino** [magarveylab/prism-releases#4]
Hi,

I think you should add some guideline in the README, like that we need to use the WebContent directory as an argument when running the jar from command line.

We still get the following error while running the program.. we added muscle (not in the README) as a dependency but there's no tests/active_site/muscle_check.sh in the WebContent directory of the project.

Are we doing something wrong ? 

thank you

```
SEVERE: Cannot run program "/home/rogia/prism-releases-master/prism/WebContent/tests/active_site/muscle_check.sh": error=2, No such file or directory
java.io.IOException: Cannot run program "/home/rogia/prism-releases-master/prism/WebContent/tests/active_site/muscle_check.sh": error=2, No such file or directory
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
    at ca.mcmaster.magarveylab.prism.util.PrismProcessBuilder.run(PrismProcessBuilder.java:39)
    at ca.mcmaster.magarveylab.prism.PrismDependencyCheck.checkMuscle(PrismDependencyCheck.java:444)
    at ca.mcmaster.magarveylab.prism.PrismDependencyCheck.checkBinaryDependencies(PrismDependencyCheck.java:199)
    at ca.mcmaster.magarveylab.prism.PrismDependencyCheck.run(PrismDependencyCheck.java:61)
    at ca.mcmaster.magarveylab.prism.Prism.checkDependencies(Prism.java:113)
    at ca.mcmaster.magarveylab.prism.Prism.run(Prism.java:75)
    at ca.mcmaster.magarveylab.prism.PrismDesktop.main(PrismDesktop.java:101)
Caused by: java.io.IOException: error=2, No such file or directory
    at java.lang.UNIXProcess.forkAndExec(Native Method)
    at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
    at java.lang.ProcessImpl.start(ProcessImpl.java:134)
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
    ... 7 more

EXCEPTION: java.io.IOException: Cannot run program "/home/rogia/prism-releases-master/prism/WebContent/tests/active_site/muscle_check.sh": error=2, No such file or directory

java.io.IOException: Cannot run program "/home/rogia/prism-releases-master/prism/WebContent/tests/active_site/muscle_check.sh": error=2, No such file or directory
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
    at ca.mcmaster.magarveylab.prism.util.PrismProcessBuilder.run(PrismProcessBuilder.java:39)
    at ca.mcmaster.magarveylab.prism.PrismDependencyCheck.checkMuscle(PrismDependencyCheck.java:444)
    at ca.mcmaster.magarveylab.prism.PrismDependencyCheck.checkBinaryDependencies(PrismDependencyCheck.java:199)
    at ca.mcmaster.magarveylab.prism.PrismDependencyCheck.run(PrismDependencyCheck.java:61)
    at ca.mcmaster.magarveylab.prism.Prism.checkDependencies(Prism.java:113)
    at ca.mcmaster.magarveylab.prism.Prism.run(Prism.java:75)
    at ca.mcmaster.magarveylab.prism.PrismDesktop.main(PrismDesktop.java:101)
Caused by: java.io.IOException: error=2, No such file or directory
    at java.lang.UNIXProcess.forkAndExec(Native Method)
    at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
    at java.lang.ProcessImpl.start(ProcessImpl.java:134)
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
    ... 7 more
```

**Comment by nishanthmerwin** [comment]
Hi,

Can you add the CLI commands that you're using right now? I can add the `-r <WebContentDirectory>` part to the README.

Regarding this stack trace, I noticed that the version of the PRISM jar attached in the releases was actually out of sync with the version of this repo. I've updated that, and you shouldn't need this test anymore.

**Comment by zorino** [comment]
Hi, 

thanks for the quick response,

this is the command we are using -

`java -jar prism.jar  -a -p -f GCF_000721175.1_ASM72117v1_genomic.fasta -all  -w 10000 -r prism/WebContent/`

The jar file fix worked, since we completed the run successfully.

However, it didn't identify any clusters while your web server identified several clusters for the same fasta file. Maybe we missed something in the command line.

See the json result from CLI https://gist.github.com/zorino/6b8e026c426b927d6e243936d1793c12
and the json result from web server https://gist.github.com/zorino/17ddf1a215579a8663aa613e7dce927c

**Comment by zorino** [comment]
Never mind the -all option is not there in the new version.
I'm closing the issue, thanks.
